--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.6
--  \   \         Application : xaw2vhdl
--  /   /         Filename : LatheClk.vhd
-- /___/   /\     Timestamp : 04/09/2015 11:13:28
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st C:\Development\Xilinx\LatheCtl\.\LatheClk.xaw C:\Development\Xilinx\LatheCtl\.\LatheClk
--Design Name: LatheClk
--Device: xc3s250e-5tq144
--
-- Module LatheClk
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity LatheClk is
 port ( CLK_IN   : in    std_logic; 
        RESET    : in    std_logic; 
        CLK_OUT  : out   std_logic; 
        LOCKED   : out   std_logic);
end LatheClk;

architecture Behavioral of LatheClk is

 signal CLKFB_IN   : std_logic;
 signal CLK0_BUF   : std_logic;
 signal GND_BIT    : std_logic;

begin

 GND_BIT <= '0';
 CLK_OUT <= CLKFB_IN;

 CLK0_BUFG_INST : BUFG
  port map (
   I => CLK0_BUF,
   O => CLKFB_IN);
 
 DCM_SP_INST : DCM_SP
  generic map(
   CLK_FEEDBACK => "1X",
   CLKDV_DIVIDE => 2.0,
   CLKFX_DIVIDE => 1,
   CLKFX_MULTIPLY => 4,
   CLKIN_DIVIDE_BY_2 => FALSE,
   CLKIN_PERIOD => 20.000,
   CLKOUT_PHASE_SHIFT => "NONE",
   DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
   DFS_FREQUENCY_MODE => "LOW",
   DLL_FREQUENCY_MODE => "LOW",
   DUTY_CYCLE_CORRECTION => TRUE,
   FACTORY_JF => x"C080",
   PHASE_SHIFT => 0,
   STARTUP_WAIT => FALSE)
  port map (
   CLKFB => CLKFB_IN,
   CLKIN => CLK_IN,
   DSSEN => GND_BIT,
   PSCLK => GND_BIT,
   PSEN => GND_BIT,
   PSINCDEC => GND_BIT,
   RST => RESET,
   CLKDV => open,
   CLKFX => open,
   CLKFX180 => open,
   CLK0 => CLK0_BUF,
   CLK2X => open,
   CLK2X180 => open,
   CLK90 => open,
   CLK180 => open,
   CLK270 => open,
   LOCKED => LOCKED,
   PSDONE => open,
   STATUS => open);
 
end Behavioral;


