bitList =\
[\
 "z control register",
 ["ZRST","(1 << 0)","reset flag"],
 ["ZSTART","(1 << 1)","start z"],
 ["ZSRC_SYN","(1 << 2)","run z synchronized"],
 ["ZSRC_FRQ","(0 << 2)","run z from clock source"],
 ["ZDIR_POS","(1 << 3)","move z in positive direction"],
 ["ZDIR_NEG","(0 << 3)","move z in negative direction"],
 ["ZSET_LOC","(1 << 4)","set z location"],
 ["ZBACKL","(1 << 5)","backlash move no position update"],
 ["ZWAIT_SYN","(1 << 6)","wait for sync to start"],
 ["ZPULSE_MULT","(1 << 7)","enable pulse multiplier"],
 ["ZDIR_ENC","(1 << 7)","z direction from encoder"],
 "# x control register",
 ["XRST","(1 << 0)","x reset"],
 ["XSTART","(1 << 1)","start x"],
 ["XSRC_SYN","(1 << 2)","run x synchronized"],
 ["XSRC_FRQ","(0 << 2)","run x from clock source"],
 ["XDIR_POS","(1 << 3)","x positive direction"],
 ["XDIR_NEG","(0 << 3)","x negative direction"],
 ["XSET_LOC","(1 << 4)","set x location"],
 ["XBACKL","(1 << 5)","x backlash move"],
 "# taper control register",
 ["TENA","(1 << 0)","taper enable"],
 ["TZ","(1 << 1)","one for taper z"],
 ["TX","(0 << 1)","zero for taper x"],
 "# position control register",
 ["PRST","(1 << 0)","reset position"],
 ["PLIM","(1 << 1)","set flag on limit reached"],
 ["PZERO","(1 << 2)","set flag on zero reached"],
 "# debug control register",
 ["DBG_ENA","(1 << 0)","enable debugging"],
 ["DBG_DIR","(1 << 1)","debug direction"],
 ["DBG_COUNT","(1 << 2)","count number of debug clocks"],
 ["DBG_INIT","(1 << 3)","init z modules"],
 ["DBG_RSYN","(1 << 4)","running in sync mode"],
 ["DBG_MOVE","(1 << 5)","route debug clock to z AxisMove"]
]
